project/app/urls.py
from django.urls import path
from .views import LoginView, RegisterView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
]

project/myapp/urls.py
# urls.py
from django.urls import path
from .views import  estadomovil, perfil_usuario, ultimo_pedido, pedidos_usuario, detailpedidos, cancelar_pedido, pedido_detalle, verificar_estado_pedido, estado_pedido, pedidos_completados, marcar_pedido_completado, inicio, crear_pedido, pedido_exito, pedidos_conductor
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('add_pedido/', crear_pedido, name='add_pedido'),
    path('pedido_exito/', pedido_exito, name='pedido_exito'),  # Añadir esta línea
    path('appmovil/', inicio, name='inicio'),
    path('pedidos-conductor/', pedidos_conductor, name='pedidos_conductor'),
    path('pedidos/completar/<int:pedido_id>/', marcar_pedido_completado, name='marcar_pedido_completado'),
    path('pedidos_completados/', pedidos_completados, name='pedidos_completados'),
    path('estado_pedido/<int:pedido_id>/', estado_pedido, name='estado_pedido'),
    path('verificar_estado_pedido/<int:pedido_id>/', verificar_estado_pedido, name='verificar_estado_pedido'),
    path('pedido/<int:pedido_id>/', pedido_detalle, name='pedido_detalle'),
    path('cancelar_pedido/<int:pedido_id>/', cancelar_pedido, name='cancelar_pedido'),
    path('mis_pedidos/', pedidos_usuario, name='pedidos_usuario'),
    path('pedidos/<int:pedido_id>/', detailpedidos, name='detailpedidos'),  # Ejemplo para la vista de detalle
    path('ultimo_pedido/', ultimo_pedido, name='ultimo_pedido'),
    path('perfil/', perfil_usuario, name='perfil_usuario'),
    path('mvehiculo/<int:vehiculo_id>/cambiar_estado/', estadomovil, name='estadomovil'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')), 
    path('', include('panel.urls')),
    path('', include('myapp.urls')),
    path('', include('pedidos.urls')),
    path('api/', include('app.urls')), 
     
]

project/myapp/models.py
from django.db import models

# Create your models here.

project/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Rol(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class CustomUser(AbstractUser):
    id_rol = models.ForeignKey(Rol, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    telf = models.CharField(max_length=15, null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', null=True, blank=True)  # Campo de imagen opcional    
    
    def save(self, *args, **kwargs):
        # Verifica si el número de teléfono no está vacío
        if self.telf:
            # Elimina espacios en blanco y el signo '+' si existe
            self.telf = self.telf.replace(" ", "").replace("+", "")
            # Si el número no comienza con '591', añade el prefijo
            if not self.telf.startswith("591"):
                self.telf = "+591" + self.telf
        # Llama al método save de la clase base para guardar el objeto
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

class Cliente(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    ci = models.CharField(max_length=20)

    def __str__(self):
        return f"Cliente: {self.user.username}"

class Conductor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    num_lice = models.CharField(max_length=20)
    categoria = models.CharField(max_length=10)

    def __str__(self):
        return f"Conductor: {self.user.username}"

class TipoVehiculo(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Vehiculo(models.Model):
    estado = models.CharField(max_length=100, default='fuera de servicio')
    placa = models.CharField(max_length=20)
    modelo = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    anio = models.PositiveIntegerField()
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    tipo_vehiculo = models.ForeignKey(TipoVehiculo, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='vehiculos/', null=True, blank=True)  # Añade este campo
    

    def __str__(self):
        return f"Vehículo {self.placa} - Modelo: {self.modelo}"

class TipoServicio(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    conductor = models.ForeignKey(Conductor, null=True, on_delete=models.CASCADE)
    servicio = models.ForeignKey(TipoServicio, on_delete=models.CASCADE)
    fecha_hora_inicio = models.DateTimeField()
    fecha_hora_fin = models.DateTimeField(null=True)
    estado = models.CharField(max_length=100, default='pendiente')  # Valor por defecto
    origen = models.URLField(null=True)
    motivo_rechazo = models.CharField(max_length=255, null=True, blank=True)  # Añade este campo

    def __str__(self):
        return f"Pedido {self.id} - Cliente: {self.cliente.user.username} - Conductor: {self.conductor.user.username}"

project/myapp/forms.py
from django import forms
from usuarios.models import Pedido
from django.utils import timezone

class PedidoForm(forms.ModelForm):
    origen = forms.URLField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Introduce la URL de Google Maps'})
    )

    class Meta:
        model = Pedido
        fields = ['servicio', 'origen']  # Excluye 'fecha_hora_fin' y 'conductor'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Usuario logueado
        super().__init__(*args, **kwargs)
        if self.user:
            self.instance.cliente = self.user.cliente  # Asume que hay una relación uno a uno

    def save(self, commit=True):
        pedido = super().save(commit=False)
        if commit:
            pedido.fecha_hora_inicio = timezone.now()  # Establece la hora actual
            if commit:
                pedido.save()
        return pedido

project/myapp/views.py
from django.shortcuts import render, redirect
from .forms import PedidoForm
from usuarios.models import TipoServicio, Vehiculo, Cliente
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from usuarios.models import Pedido, Conductor, Cliente, Vehiculo
from django.http import HttpResponseForbidden, HttpResponseNotFound
from django.utils import timezone
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages


@login_required
def detailpedidos(request, pedido_id):
    # Obtiene el pedido específico o muestra una página 404 si no existe
    pedido = get_object_or_404(Pedido, id=pedido_id)

    # Verifica si el usuario está autorizado a ver el pedido (opcional)
    if pedido.cliente.user != request.user:
        return render(request, '403.html', status=403)  # Página de acceso denegado

    context = {
        'pedido': pedido,
    }
    return render(request, 'detailpedidos.html', context)
@login_required
def pedidos_usuario(request):
    try:
        # Obtiene el cliente relacionado con el usuario en sesión
        cliente = Cliente.objects.get(user=request.user)
        # Filtra los pedidos relacionados con el cliente y ordénalos de más reciente a más antiguo
        pedidos = Pedido.objects.filter(cliente=cliente).order_by('-fecha_hora_inicio')
    except Cliente.DoesNotExist:
        # Si el usuario no es un cliente, no tiene pedidos
        pedidos = []

    context = {
        'pedidos': pedidos,
    }
    return render(request, 'pedidos_usuario.html', context)
@login_required
def pedidos_conductor(request):
    user = request.user

    # Verifica si el usuario es un conductor
    if not hasattr(user, 'conductor'):
        return redirect('inicio')  # Redirige a otra página si el usuario no es un conductor

    # Obtiene el conductor del usuario logueado
    conductor = Conductor.objects.get(user=user)

    # Obtiene los pedidos asignados al conductor con estado "en progreso"
    pedidos = Pedido.objects.filter(conductor=conductor, estado='En Progreso')

    return render(request, 'pedidos_conductor.html', {'pedidos': pedidos})

def marcar_pedido_completado(request, pedido_id):
    try:
        # Obtener el pedido o lanzar 404 si no existe
        pedido = get_object_or_404(Pedido, id=pedido_id)

        # Verificar que el conductor del pedido sea el usuario actual
        if pedido.conductor.user == request.user:
            # Cambiar el estado del pedido a "Completado"
            pedido.estado = 'Completado'
            pedido.fecha_hora_fin = timezone.now()
            pedido.save()

            # Cambiar el estado del vehículo del conductor a "activo"
            vehiculo = get_object_or_404(Vehiculo, conductor=pedido.conductor)
            vehiculo.estado = 'activo'
            vehiculo.save()

            # Redirigir a la página de pedidos asignados
            return redirect('pedidos_conductor')
        else:
            return HttpResponseForbidden("No tienes permiso para completar este pedido.")
    except Pedido.DoesNotExist:
        return HttpResponseNotFound("Pedido no encontrado.")

def crear_pedido(request):
    if request.method == 'POST':
        form = PedidoForm(request.POST, user=request.user)
        if form.is_valid():
            pedido = form.save()
            return redirect('estado_pedido', pedido_id=pedido.id)
    else:
        form = PedidoForm(user=request.user)
        
    servicios = TipoServicio.objects.all()
    return render(request, 'add_pedido.html', {'form': form, 'servicios': servicios})

def pedido_exito(request):
    ultimo_pedido = Pedido.objects.latest('fecha_hora_inicio')
    return render(request, 'pedido_exito.html', {'pedido': ultimo_pedido})

def inicio(request):
    return render(request, 'inicio.html')
@login_required

def pedidos_completados(request):
    user = request.user

    # Verifica si el usuario es un conductor
    if not hasattr(user, 'conductor'):
        return redirect('inicio')  # Redirige a otra página si el usuario no es un conductor

    # Obtiene el conductor del usuario logueado
    conductor = Conductor.objects.get(user=user)

    # Obtiene los pedidos asignados al conductor con estado "Completado" o "Cancelado"
    pedidos = Pedido.objects.filter(conductor=conductor, estado__in=['Completado', 'Cancelado'])

    return render(request, 'pedidos_completados.html', {'pedidos': pedidos})

def verificar_estado_pedido(request, pedido_id):
    try:
        pedido = Pedido.objects.get(id=pedido_id)
        response_data = {
            'estado': pedido.estado,
        }
        if pedido.estado == 'Rechazado':
            response_data['motivo'] = pedido.motivo_rechazo  # Asegúrate de que el modelo `Pedido` tiene este campo
        return JsonResponse(response_data)
    except Pedido.DoesNotExist:
        return JsonResponse({'error': 'Pedido no encontrado'}, status=404)
   
def estado_pedido(request, pedido_id):
    return render(request, 'estado_pedido.html', {'pedido_id': pedido_id})

def pedido_detalle(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id)
    return render(request, 'pedido_detalle.html', {'pedido': pedido})

@require_POST
def cancelar_pedido(request, pedido_id):
    try:
        # Obtener el pedido correspondiente
        pedido = Pedido.objects.get(id=pedido_id)

        # Cambiar el estado del pedido a 'Cancelado'
        pedido.estado = 'Cancelado'
        pedido.fecha_hora_fin = timezone.now()

        # Cambiar el estado del vehículo a 'activo' si hay un conductor asignado
        if pedido.conductor:  # Verifica que el pedido tiene un conductor asignado
            vehiculo = pedido.conductor.vehiculo  # Accede directamente al vehículo del conductor
            
            if vehiculo.estado == 'ocupado':  # Verifica que el vehículo esté ocupado
                vehiculo.estado = 'activo'  # Cambia el estado del vehículo a 'activo'
                vehiculo.save()  # Guarda los cambios del vehículo

        # Guarda los cambios del pedido
        pedido.save()
        return JsonResponse({'success': True})
    except Pedido.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Pedido no encontrado'})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})
    
def ultimo_pedido(request):
    # Obtener el último pedido
    ultimo_pedido = Pedido.objects.latest('fecha_hora_inicio')
    
    if request.method == 'POST':
        # Cancelar el pedido si el estado es "En progreso"
        if ultimo_pedido.estado.lower() == 'en progreso':
            ultimo_pedido.estado = 'Cancelado'
            ultimo_pedido.fecha_hora_fin = timezone.now()  # Establecer la hora de finalización
            ultimo_pedido.save()
            messages.success(request, 'El pedido ha sido cancelado exitosamente.')
            return redirect('ultimo_pedido')

    return render(request, 'ultimo_pedido.html', {'pedido': ultimo_pedido})

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required
def perfil_usuario(request):
    user = request.user  # Usuario actualmente autenticado

    # Verificar si el usuario tiene información adicional en un modelo relacionado
    try:
        if hasattr(user, 'cliente'):
            perfil = user.cliente
        elif hasattr(user, 'conductor'):
            perfil = user.conductor
        elif hasattr(user, 'comun'):
            perfil = user.comun
        else:
            perfil = None
    except Exception:
        perfil = None

    if request.method == 'POST':
        # Cambiar imagen de perfil
        nueva_imagen = request.FILES.get('profile_image')
        nuevo_ci = request.POST.get('ci')

        # Actualizar imagen de perfil
        if nueva_imagen:
            user.profile_image = nueva_imagen  # Actualizar el campo 'profile_image'
            user.save()
            messages.success(request, 'Imagen de perfil actualizada exitosamente.')

        # Agregar CI si está vacío
        if perfil and not perfil.ci and nuevo_ci:
            perfil.ci = nuevo_ci
            perfil.save()
            messages.success(request, 'CI agregado exitosamente.')
        elif not nuevo_ci and perfil and not perfil.ci:
            messages.warning(request, 'Por favor, proporciona un valor para el CI.')

        return redirect('perfil_usuario')  # Redirigir a la misma página después de guardar cambios

    context = {
        'user': user,
        'perfil': perfil,
    }

    return render(request, 'perfil.html', context)

    user = request.user  # El usuario actualmente autenticado

    # Si tienes información adicional en modelos relacionados, puedes obtenerla así
    try:
        if hasattr(user, 'cliente'):
            perfil = user.cliente
        elif hasattr(user, 'conductor'):
            perfil = user.conductor
        else:
            perfil = None
    except:
        perfil = None
    
    context = {
        'user': user,
        'perfil': perfil,
    }
    
    return render(request, 'perfil.html', context)

from django.views.decorators.csrf import csrf_exempt

def estadomovil(request, vehiculo_id):
    vehiculo = get_object_or_404(Vehiculo, id=vehiculo_id)
    if request.method == 'POST':
        nuevo_estado = request.POST.get('nuevo_estado')
        vehiculo.estado = nuevo_estado
        vehiculo.save()
    return redirect(request.META.get('HTTP_REFERER'))

project/myapp/templates/add_pedido.html
{% extends 'basem.html' %}

{% block title %}Crear Pedido{% endblock %}

{% block content %}
<style>
    /* Estilos generales */
    body, html {
        margin: 0;
        padding: 0;
        height: 100%;
        font-family: 'Roboto', sans-serif;
        background-color: #f4f4f4;
    }

    .form-content {
        width: 100%;
        max-width: 480px;
        margin: 20px auto;
        padding: 20px;
        box-sizing: border-box;
        background: #ffffff;
        border-radius: 10px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        color: #333;
        font-size: 24px;
        margin-bottom: 20px;
        font-weight: bold;
    }

    .servicio-container {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
        justify-content: center;
        margin-bottom: 20px;
    }

    .servicio-item {
        flex: 1 1 calc(50% - 10px); /* Dos botones por fila */
        max-width: calc(50% - 10px); /* Ajuste de tamaño para el espacio */
        border: 2px solid #e0e0e0;
        border-radius: 10px;
        overflow: hidden;
        text-align: center;
        cursor: pointer;
        transition: transform 0.3s, background-color 0.3s, border-color 0.3s;
        background: #ffffff;
        padding: 8px; /* Reduce el padding */
        box-sizing: border-box;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
    }

    .servicio-item:hover {
        transform: scale(1.03);
        background-color: #f8f9fa;
        border-color: #007bff;
    }

    .servicio-item img {
        width: 20%;
        height: 80px;
        object-fit: cover;
        border-radius: 8px;
    }

    .servicio-item p {
        margin: 10px 0 0;
        font-weight: 600;
        color: #333;
        font-size: 14px;
    }

    .form-group {
        margin-top: 20px;
        display: flex;
        flex-direction: column;
    }

    .form-group label {
        font-weight: bold;
        margin-bottom: 5px;
        font-size: 16px;
    }

    .form-group input[type="text"],
    .form-group input[type="url"] {
        width: 100%;
        padding: 12px;
        border: 1px solid #ced4da;
        border-radius: 8px;
        font-size: 16px;
        color: #495057;
        background-color: #f9f9f9;
        transition: border-color 0.3s, box-shadow 0.3s;
    }

    .form-group input[type="text"]:focus,
    .form-group input[type="url"]:focus {
        border-color: #007bff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

    .btn2 {
        width: 100%;
        padding: 12px;
        background-color: #28a745; /* Verde para el botón de ubicación */
        color: #fff;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s, box-shadow 0.3s;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        text-align: center;
    }
    .btn {
        width: 100%;
        padding: 12px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        font-size: 18px;
        margin-top: 20px;
        transition: background-color 0.3s, box-shadow 0.3s;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        text-align: center;
    }

    .btn:hover {
        background-color: #0056b3;
        box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
    }

    .btn:active {
        background-color: #004494;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3) inset;
        transform: translateY(2px);
    }

    /* Media Queries */
    @media (max-width: 576px) {
        .servicio-item {
            flex: 1 1 100%;
            max-width: 100%;
        }

        .form-content {
            padding: 10px;
        }

        .btn {
            font-size: 16px;
        }

        .servicio-item img {
            height: 60px;
        }
    }
</style>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            {% load static %}
            {% for servicio in servicios %}
                    <label class="servicio-item d-block">
                        <input type="radio" name="servicio" value="{{ servicio.id }}" required style="display:none;">
                        <img src="{% static 'images/'|add:servicio.nombre|add:'.png' %}" alt="{{ servicio.nombre }}">
                        <p>{{ servicio.nombre }}</p>
                    </label>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.origen.label_tag }}
            <div style="display: flex; align-items: center;">
                {{ form.origen }}
                <button type="button" class="btn2" style="margin-left: 10px;" onclick="requestLocationPermission()">Usar mi ubicación</button>
            </div>
        </div>
        <button type="submit" class="btn">Pedir</button>
    </form>


<script>
    function requestLocationPermission() {
        if (navigator.geolocation) {
            navigator.permissions.query({ name: 'geolocation' }).then(function(permissionStatus) {
                if (permissionStatus.state === 'denied') {
                    alert("El acceso a la ubicación ha sido denegado. Por favor, permite el acceso a la ubicación en la configuración de tu navegador.");
                    return;
                }

                navigator.geolocation.getCurrentPosition(
                    function(position) {
                        var latitude = position.coords.latitude;
                        var longitude = position.coords.longitude;
                        var locationURL = "https://www.google.com/maps?q=" + latitude + "," + longitude;
                        document.querySelector('input[name="origen"]').value = locationURL;
                    },
                    function(error) {
                        switch(error.code) {
                            case error.PERMISSION_DENIED:
                                alert("Permiso denegado. Debes permitir el acceso a la ubicación para usar esta función.");
                                break;
                            case error.POSITION_UNAVAILABLE:
                                alert("La información de ubicación no está disponible. Intenta nuevamente.");
                                break;
                            case error.TIMEOUT:
                                alert("La solicitud para obtener la ubicación ha caducado. Intenta nuevamente.");
                                break;
                            case error.UNKNOWN_ERROR:
                                alert("Ocurrió un error desconocido. Por favor, inténtalo de nuevo.");
                                break;
                        }
                    }
                );
            }).catch(function(error) {
                alert("Ocurrió un error al solicitar el permiso de ubicación.");
            });
        } else {
            alert("La geolocalización no es soportada por este navegador.");
        }
    }
</script>
{% endblock %}

{% block extra_css %}

{% endblock %}

project/myapp/templates/inicio.html
{% extends 'basem.html' %}

{% block title %}Inicio{% endblock %}

{% block header %}
    Proyecto Tecnico de grado
{% endblock %}

{% block content %}
<style>

    .btn-custom {
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 12px 24px;
        font-size: 1.125rem;
        transition: background-color 0.3s ease;
    }

    .btn-custom:hover {
        background-color: #0056b3;
    }
    .footer-image {
        width: 100%;
        height: auto;
        max-width: 300px; /* Ajusta según tus necesidades */
        display: block;
        margin: 0 auto;
    }
</style>
{% load static %}

    <div class="text-center">
        <h2>Bienvenido al Sindicato de Radiotrasporte</h2>
        <h2>URINZAYA</h2>

        <p>Gracias por elegir nuestro servicio de transporte. Aquí puedes solicitar un transporte de manera rápida y sencilla desde la comodidad de tu dispositivo móvil.</p>
              
        <div class="sidebar-footer">                
            <img src="{% static 'images/logo5.png' %}" alt="Imagen sin fondo" class="footer-image">
        </div>
        {% if request.user.is_authenticated and request.user.cliente %}
            <a href="{% url 'add_pedido' %}" class="btn btn-custom btn-lg">Solicitar Servicio</a>
        {% endif %}

        {% if request.user.is_authenticated and request.user.conductor %}
            <a class="btn btn-info" href="{% url 'pedidos_conductor' %}">Ver Pedidos Asignados</a>
        {% endif %}
    </div>
{% endblock %}

project/myapp/templates/perfil.html
{% extends 'basem.html' %}

{% block title %}Perfil de {{ user.username }}{% endblock %}

{% block header_title %}Perfil de {{ user.username }}{% endblock %}

{% block content %}
{% load static %}

<div class="container my-5">
    <div class="card shadow-sm rounded-lg">
        <div class="card-header bg-primary text-white text-center">
            <h5 class="mb-0">Información del Usuario</h5>
        </div>
        <div class="card-body">
            <div class="text-center">
                {% if user.profile_image %}
                    <img src="{{ user.profile_image.url }}" alt="Imagen de Perfil" class="img-fluid img-thumbnail rounded-circle" style="max-width: 150px; max-height: 150px;">
                {% else %}
                    <img src="{% static 'default-profile.png' %}" alt="Imagen de Perfil" class="img-fluid img-thumbnail rounded-circle" style="max-width: 150px; max-height: 150px;">
                {% endif %}
            </div>
            
            <!-- Formulario para cambiar imagen de perfil -->
            <div class="mt-3">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="profile_image">Cambiar imagen de perfil:</label>
                        <input type="file" name="profile_image" id="profile_image" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Actualizar Imagen</button>
                </form>
            </div>

            <div class="mt-3">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <th class="text-start">Nombre de usuario:</th>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <th class="text-start">Nombre completo:</th>
                            <td>{{ user.first_name }} {{ user.last_name }}</td>
                        </tr>
                    </tbody>
                </table>

                {% if user.id_rol.nombre == 'conductor' %}
                    {% if user.conductor.vehiculo_set.exists %}
                        <div class="mt-4">
                            <h5 class="mb-3">Información del Vehículo</h5>
                            {% for vehiculo in user.conductor.vehiculo_set.all %}
                                <div class="mb-4">
                                    <div class="text-center">
                                        {% if vehiculo.imagen %}
                                            <img src="{{ vehiculo.imagen.url }}" alt="Imagen del Vehículo" class="img-fluid img-thumbnail rounded" style="max-width: 200px; max-height: 200px;">
                                        {% else %}
                                            <img src="{% static 'default-vehiculo.png' %}" alt="Imagen del Vehículo" class="img-fluid img-thumbnail rounded" style="max-width: 200px; max-height: 200px;">
                                        {% endif %}
                                    </div>
                                    <table class="table table-borderless mt-3">
                                        <tbody>
                                            <tr>
                                                <th class="text-start">Estado:</th>
                                                <td>{{ vehiculo.estado }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-start">Tipo de Vehículo:</th>
                                                <td>{{ vehiculo.tipo_vehiculo.nombre }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="mt-4 text-center">
                                        <form action="{% url 'estadomovil' vehiculo.id %}" method="post">
                                            {% csrf_token %}
                                            {% if vehiculo.estado == 'activo' %}
                                                <input type="hidden" name="nuevo_estado" value="inactivo">
                                                <button type="submit" class="btn btn-warning">Cambiar a Inactivo</button>
                                            {% else %}
                                                <input type="hidden" name="nuevo_estado" value="activo">
                                                <button type="submit" class="btn btn-success">Cambiar a Activo</button>
                                            {% endif %}
                                        </form>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="mt-4">
                            <p>Este conductor no tiene ningún vehículo registrado.</p>
                        </div>
                    {% endif %}
                {% elif user.id_rol.nombre == 'comun' and user.cliente %}
                    <div class="mt-4">
                        <h5 class="mb-3">Información del Cliente</h5>
                        <p><strong>Cédula de Identidad:</strong> 
                            {% if user.cliente.ci %}
                                {{ user.cliente.ci }}
                            {% else %}
                                <form method="POST" class="mt-3">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="ci">Ingresar Cédula de Identidad:</label>
                                        <input type="text" name="ci" id="ci" class="form-control" placeholder="Ingrese su CI">
                                    </div>
                                    <button type="submit" class="btn btn-success mt-3">Agregar CI</button>
                                </form>
                            {% endif %}
                        </p>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="card-footer bg-light text-center">
            <a href="{% url 'inicio' %}" class="btn btn-secondary mx-1">Volver</a>
        </div>
    </div>
</div>

{% endblock %}